const KEY_REFERENCE_TYPE = {
  SEED: 'SEED',
  KEY_LABEL: 'KEY_LABEL',
};

const KEY_ALGO = {
  SECP256K1: 'SECP256K1',
  ED25519: 'ED25519',
};

const SUPPORTED_KMS = {
  LOCAL_KMS: 'LOCAL_KMS',

  AWS_KMS: 'AWS_KMS',
  AWS_CLOUDHSM_KMS: 'AWS_CLOUDHSM_KMS',

  // CLOUDHSM_KMS: 'CLOUDHSM_KMS',
  // HASHICORP_VAULT_KMS: 'HASHICORP_KMS',
  // THALES_LUNA_KMS: 'LUNA_LUNA_KMS',
  // UTIMACO_KMS: 'UTIMACO_KMS',
  // GOOGLE_KMS: 'GOOGLE_KMS',
  // AZURE_KMS: 'AZURE_KMS',
};

module.exports = {
  KEY_REFERENCE_TYPE,
  KEY_ALGO,
  SUPPORTED_KMS,
};
